#
# Fuel Bar and Speed will be displayed in the following format:
# "[{fuelbars}] | {speed} b/s"
#
# Formats:
# Colors: &7
# RGB: &x&r&r&g&g&b&b
#

Config:
  # Colors for the available fuel
  fuelLeftColor: '&x&f&f&c&5&4&f'
  
  # Colors for the empty fuel
  fuelSpentColor: '&7'
  
  # Colors for the "[ ] | /"
  seperatorColors: '&8'
  
  # Color for the {speed}
  speedColor: '&x&f&f&c&5&4&f'
  
  # Color for the "b s"
  blocksPerSecondColor: '&x&f&f&c&5&4&f'